version: "3.7"

services:
  managedhost-app-1:
    container_name: managedhost-app-1
    build: 
      context: managed-host/alpine/app1
    restart: unless-stopped
    network_mode: "bridge"
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./secrets/id_rsa_container.pub:/root/.ssh/authorized_keys
    ports:
      - "3000:3000"  # Web port mapping
      - "2223:2223"    # SSH port mapping

  managedhost-app-2:
    container_name: managedhost-app-2
    build: 
      context: managed-host/alpine/app2
    restart: unless-stopped
    network_mode: "bridge"
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./secrets/id_rsa_container.pub:/root/.ssh/authorized_keys
    ports:
      - "3001:3000"  # Web port mapping
      - "2224:2224"    # SSH port mapping

  managedhost-app-3:
    container_name: managedhost-app-3
    build: 
      context: managed-host/alpine/app3
    restart: unless-stopped
    network_mode: "bridge"
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./secrets/id_rsa_container.pub:/root/.ssh/authorized_keys
    ports:
      - "3002:3000"  # Web port mapping
      - "2225:2225"    # SSH port mapping