ungrouped:
  hosts: {}

app_group:
  hosts:
    managedhost-app-1:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2223
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3

    managedhost-app-2:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2224
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3

    managedhost-app-3:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2225
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3

